<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ODataFilter.MudBlazor</RootNamespace>
    <AssemblyName>ODataFilter.MudBlazor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ODataFilter.Core\ODataFilter.Core.csproj" />
  </ItemGroup>

</Project>
