<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ODataFilter.MudBlazor.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="AwesomeAssertions.Analyzers" PrivateAssets="all" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.analyzers" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ODataFilter.MudBlazor\ODataFilter.MudBlazor.csproj" />
  </ItemGroup>

</Project>
