<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ClaudeMem.Admin.Ui</RootNamespace>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <MudAllowedAttributePattern>LowerCase</MudAllowedAttributePattern>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClaudeMem.Admin.Api.Contracts\ClaudeMem.Admin.Api.Contracts.csproj" />
  </ItemGroup>

</Project>
