<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ClaudeMem.Admin.Api.Contracts.Generator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NJsonSchema.CodeGeneration.CSharp" />
    <PackageReference Include="NSwag.CodeGeneration.CSharp" />
    <PackageReference Include="NSwag.Core.Yaml" />
    <PackageReference Include="System.CodeDom" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CodeGen\Client\Templates\Class.Constructor.Record.liquid" />
  </ItemGroup>

</Project>
