<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ODataFilter.EfCore</RootNamespace>
    <AssemblyName>ODataFilter.EfCore</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gridify" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ODataFilter.Core\ODataFilter.Core.csproj" />
  </ItemGroup>

</Project>
