<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ODataFilter.Core</RootNamespace>
    <AssemblyName>ODataFilter.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.OData.Core" />
    <PackageReference Include="SqlKata" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ODataFilter.EfCore" />
    <InternalsVisibleTo Include="ODataFilter.MudBlazor" />
  </ItemGroup>

</Project>
